
(define (domain cocina)
 (:requirements :typing :fluents :equality)
 (:types mano almacen alimento ingrediente acompanyante receta botella utensilio vitro plato)
 
 (:predicates 
			(listo ?r - receta)
			(ocupada ?m - mano)
			(con_acompanyante ?receta)
			(sin_vitro ?receta)
			(abierto ?x - almacen)		
			(en_mano ?a - alimento)
			(agarrado ?i - ingrediente)
			(sujetado ?h - acompanyante)
			(vitro_encendida ?v - vitro)			
			(cogido ?u - utensilio)
			(en_encimera ?u - utensilio)
			(en_fregadero ?u - utensilio)
			(liquido_vertido ?u - utensilio)
			(tapada ?b - botella)
			(cogida ?b - botella)
			(vacia ?b - botella)
			(en_basura ?b - botella)			
			(en_pila ?p - plato)
			(colocado ?p - plato)			
			(guardado ?a - alimento ?x - almacen)
			(i_guardado ?i - ingrediente ?x - almacen)
			(a_guardado ?h - acompanyante ?y - almacen)
			(almacenado ?u - utensilio ?x - almacen)
			(guardada ?b - botella ?x - almacen)	
			(vitro_ocupada ?u - utensilio ?v - vitro)
			(alimento_en_vitro ?a - alimento ?u - utensilio ?v - vitro)	
			(ingrediente_en_vitro ?i - ingrediente ?u - utensilio ?v - vitro)			
			(acompanyante_en_vitro ?h - acompanyante ?u - utensilio ?v - vitro)			
			(comida_en_plato ?r - receta ?p - plato)
			(alimento_en_plato ?a - alimento ?p - plato)
			(ingrediente_en_plato ?i - ingrediente ?p - plato)
			(ingrediente_en_encimera ?i - ingrediente)
			(alimento_en_encimera ?a - alimento)
			(acompanyante_en_encimera ?h - acompanyante)

)

(:action abrir_almacen
:parameters (?x - almacen)
:precondition (not (abierto ?x))
:effect (abierto ?x)
)

(:action cerrar_almacen
:parameters (?x - almacen)
:precondition (abierto ?x)
:effect (not (abierto ?x))
)

(:action dejar_alimento
:parameters (?a - alimento ?m - mano)
:precondition (en_mano ?a)
:effect (and(alimento_en_encimera ?a)
		(not (en_mano ?a))
		(not (ocupada ?m))
		)
)

(:action dejar_ingrediente
:parameters (?i - ingrediente ?m - mano)
:precondition (agarrado ?i)
:effect (and (ingrediente_en_encimera ?i)
		(not (agarrado ?i))
		(not (ocupada ?m))
		)
)

(:action dejar_acompanyante
:parameters (?h - acompanyante ?m - mano)
:precondition (sujetado ?h)
:effect (and(acompanyante_en_encimera ?h)
		(not (sujetado ?h))
		(not (ocupada ?m))
		)
)

(:action coger_utensilio
:parameters (?u - utensilio ?m - mano ?x - almacen)
:precondition (and (abierto ?x)
		 		(almacenado ?u ?x)
        )
:effect (and (not (almacenado ?u ?x))
                      (cogido ?u)
                      (ocupada ?m)
         )
)

(:action coger_alimento
 :parameters (?a - alimento ?m - mano ?x - almacen)
 :precondition (and (abierto ?x)
 						(guardado ?a ?x)
 						(not (ocupada ?m))
                  )
 :effect (and (not (guardado ?a ?x))
                      (en_mano ?a)
                      (ocupada ?m)
                  )
)

(:action coger_ingrediente
 :parameters (?i - ingrediente ?m - mano ?x - almacen)
 :precondition (and (abierto ?x)
 				(i_guardado ?i ?x)
 		 		(not (ocupada ?m))
                  )
 :effect (and (not (i_guardado ?i ?x))
                      (agarrado ?i)
                      (ocupada ?m)
                  )
)

(:action coger_acompanyante
 :parameters (?h - acompanyante ?m - mano ?y - almacen)
 :precondition (and (abierto ?y)
 				(a_guardado ?h ?y)
 		 		(not (ocupada ?m))
                  )
 :effect (and (not (a_guardado ?h ?y))
                      (sujetado ?h)
                      (ocupada ?m)
                  )
)

(:action coger_botella
:parameters (?b - botella ?m - mano ?x - almacen)
:precondition (and (abierto ?x)
			(guardada ?b ?x)
			 	(not (ocupada ?m))
                  )
:effect (and (not (guardada ?b ?x))
                      (cogida ?b)
                      (ocupada ?m)
                  )
)

(:action destapa
:parameters (?b - botella)
:precondition (and (tapada ?b)
                    (cogida ?b)
                  )
:effect (not (tapada ?b)
                  )
)

(:action tapa
:parameters (?b - botella)
:precondition (and (not (tapada ?b))
                    (cogida ?b)
                  )
:effect (tapada ?b)
)

(:action dejar_botella
:parameters (?b - botella ?x - almacen ?m - mano)
:precondition (and (cogida ?b)
					(tapada ?b)
					(not (vacia ?b))
                  )
:effect (and (guardada ?b ?x)
            (not (cogida ?b))
            (not (ocupada ?m))
                  )
)

(:action tirar_botella
:parameters (?b - botella ?m - mano)
:precondition (and (cogida ?b)
		(vacia ?b)
        	)
:effect (and (en_basura ?b)
        	(not (cogida ?b))
        	(not (ocupada ?m))
         )
)

(:action vierte_liquido
:parameters (?b - botella ?u - utensilio ?v - vitro)
:precondition (and (not (tapada ?b))
                    (cogida ?b)
                    (not (vacia ?b))
                    (vitro_ocupada ?u ?v)
                  )
:effect (and (vacia ?b)
            (liquido_vertido ?u) 
            )
)

(:action anyade_alimento_sin_vitro
 :parameters (?a - alimento ?r -receta ?p - plato ?m - mano)
 :precondition (and (sin_vitro ?r)
 				(en_mano ?a)
                  (colocado ?p)
                  )
 :effect (and(alimento_en_plato ?a ?p)
 			(not (en_mano ?a))
 			(not (ocupada ?m))
 			)
)

(:action anyade_ingrediente_sin_vitro
 :parameters (?a - alimento ?i - ingrediente ?r -receta ?p - plato ?m - mano) 
 :precondition (and (sin_vitro ?r)
			 (alimento_en_plato ?a ?p)
 				(agarrado ?i)
                  (colocado ?p)
                  )
 :effect (and (ingrediente_en_plato ?i ?p)
 			(not (agarrado ?i))
 			(comida_en_plato ?r ?p)
 			(not (ocupada ?m))
  			(listo ?r)
 		)
)

(:action enciende_vitro
 :parameters (?v - vitro ?r -receta)
 :precondition (and (not (vitro_encendida ?v))
                  (not (sin_vitro ?r))
                  )
 :effect (vitro_encendida ?v)
)

(:action apaga_vitro
 :parameters (?v - vitro ?a - alimento ?r - receta)
 :precondition (and (vitro_encendida ?v)
 				(listo ?r))
 :effect (not (vitro_encendida ?v))
)

(:action ocupa_vitro
 :parameters (?v - vitro ?u - utensilio ?m - mano)
 :precondition (and (vitro_encendida ?v) 
 					(cogido ?u)
 					(not (vitro_ocupada ?u ?v))
 				)
 :effect 	(and (not (cogido ?u))
 		 	(vitro_ocupada ?u ?v)
			(not (ocupada ?m))
 				)
)

(:action echa_al_fuego_alimento
 :parameters (?a - alimento ?u - utensilio ?v - vitro ?m - mano)
 :precondition (and (en_mano ?a)
 					(vitro_ocupada ?u ?v)
 					(liquido_vertido ?u)
 					(vitro_encendida ?v)
 				)
 :effect (and (not (en_mano ?a))
 					(not (ocupada ?m))
 					(alimento_en_vitro ?a ?u ?v)
 				)
)

(:action echa_al_fuego_ingrediente
 :parameters (?a - alimento ?i - ingrediente ?u - utensilio ?v - vitro ?r - receta ?m - mano)
 :precondition (and (agarrado ?i)
 					(vitro_ocupada ?u ?v)
 					(liquido_vertido ?u)
 					(vitro_encendida ?v)
 				)
 :effect (and (not (agarrado ?i))
 					(not (ocupada ?m))
 					(ingrediente_en_vitro ?i ?u ?v)
 				)
)

(:action echa_al_fuego_acompanyante
 :parameters (?a - alimento ?i - ingrediente ?h - acompanyante ?u - utensilio ?v - vitro ?r - receta ?m - mano)
 :precondition (and (sujetado ?h)
 					(con_acompanyante ?r)
 					(vitro_ocupada ?u ?v)
 					(liquido_vertido ?u)
 				)
 :effect (and (not (sujetado ?h))
 					(acompanyante_en_vitro ?h ?u ?v)
					(not (ocupada ?m))
 				)
)

(:action pone_en_fregadero
 :parameters (?a - alimento ?u - utensilio ?v - vitro ?r - receta ?m - mano)
 :precondition (and (listo ?r)
 					(cogido ?u)
 				)
 :effect (and (not (en_mano ?a))
 					(not (cogido ?u))
 					(en_fregadero ?u)
 					(not (ocupada ?m))
 				)
)

(:action coloca_plato
 :parameters (?p - plato ?r - receta)
 :precondition (en_pila ?p)
 				
 :effect (and (not (en_pila ?p))
 				(colocado ?p)
 				)
)

(:action servir_alimento_ingredientes_acompanyantes
 :parameters (?a - alimento ?i - ingrediente ?h - acompanyante ?u - utensilio ?v - vitro ?p - plato ?r - receta)
 :precondition (and (acompanyante_en_vitro ?h ?u ?v)
 				(alimento_en_vitro ?a ?u ?v)
 				(ingrediente_en_vitro ?i ?u ?v)
 					(colocado ?p)
 				)
 :effect (and (comida_en_plato ?r ?p)
  				(listo ?r)
 				(not (alimento_en_vitro ?a ?u ?v))
 				 (not (ingrediente_en_vitro ?i ?u ?v))
 				  (not (acompanyante_en_vitro ?h ?u ?v))
 				)
)

(:action servir_alimento_ingredientes
 :parameters (?a - alimento ?i - ingrediente ?u - utensilio ?v - vitro ?p - plato ?r - receta)
 :precondition (and (alimento_en_vitro ?a ?u ?v)
  					(ingrediente_en_vitro ?i ?u ?v)
  				  	(not (con_acompanyante ?r))
 					(colocado ?p)
 				)
 :effect (and (comida_en_plato ?r ?p)
  				(listo ?r)
 				(not (alimento_en_vitro ?a ?u ?v))
 				 (not (ingrediente_en_vitro ?i ?u ?v))
 				)
)

(:action recoge
 :parameters (?a - alimento ?u - utensilio ?v - vitro ?r - receta ?m - mano)
 :precondition (and (listo ?r)
 					(not (cogido ?u))
 					(not (vitro_encendida ?v))
 					(vitro_ocupada ?u ?v)
 				)
 :effect (and (not (en_mano ?a))
 					(cogido ?u)
 					(not (vitro_ocupada ?u ?v))
 					(not (ocupada ?m))
 				)
)

(:action pone_en_encimera
 :parameters (?u - utensilio ?m - mano)
 :precondition (cogido ?u) 				
 :effect (and (not (cogido ?u))
 			(en_encimera ?u)
 			(not (ocupada ?m))
 			)
)

(:action recoge_de_encimera
 :parameters (?u - utensilio ?m - mano)
 :precondition (and (not (cogido ?u))
 				(not (ocupada ?m))
 				(en_encimera ?u)
 			) 				
 :effect (and (cogido ?u)
 			(not (en_encimera ?u))
 			(ocupada ?m)
 		)
)

)
